spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/btree_project?useSSL=false&serverTimezone=Asia/Seoul
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: none
  profiles:
    include:
      - aws
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      accessKey: AKIAS7D3UWOCXHVXNWTJ
      secretKey: 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
    s3:
      bucket: btreepostbucket
      region:
        static: ap-northeast-2
      stack:
        auto: false
      credentials:
        instanceProfile: true

